export {
  CreatePrimitiveCommand,
  ExtrudeFacesCommand,
  InsetFacesCommand,
  SubdivideFacesCommand,
  FillBoundaryCommand,
  BevelEdgesCommand,
  LoopCutCommand,
  DissolveEdgesCommand,
  DissolveVertexCommand,
  DissolveFaceCommand,
  CollapseEdgeCommand,
  ReverseFaceWindingCommand,
  BridgeLoopsCommand,
  SplitEdgeCommand,
  CutFaceCommand,
  ProjectUvCommand,
  AssignMaterialSlotCommand,
  AddMaterialSlotCommand,
  ReorderMaterialSlotsCommand,
  UpdateMaterialCommand,
  CreateMaterialCommand,
  AssignMaterialCommand,
  ProjectUvsCommand,
  PackUvsCommand,
  SetSeamsCommand,
  CreateSkeletonCommand,
  BindSkinCommand,
  CreateClipCommand,
  SetKeyframeCommand,
  SetTransformsCommand,
  ReparentCommand,
  DuplicateObjectsCommand,
  SetVisibilityCommand,
  GroupObjectsCommand,
  UngroupObjectsCommand,
  CreateTextureCommand,
  CreateTextureSetCommand,
  UpdateTextureSetCommand,
  DeleteTextureSetCommand,
  BindMaterialTextureSetCommand,
  CreateMaterialInstanceCommand,
  UpdateMaterialInstanceCommand,
  CreateImageDocumentCommand,
  AddImageLayerCommand,
  RemoveImageLayerCommand,
  UpdateImageLayerCommand,
  ApplyImageTilePatchesCommand,
  PaintStrokeCommand,
  SetCornerUvsCommand,
  RenameNodeCommand,
  WeldVerticesCommand,
  ExecuteKnifePlanCommand,
  KnifeCutCommand,
  HealMeshCommand,
  CatmullClarkSubdivideCommand,
  ConnectVerticesCommand,
  MergeVerticesCommand,
  TriangulateFacesCommand,
  ModelingSession,
  createModelingSession,
  FluentEditor,
  FluentMeshObject,
  createEditor,
  inspectScene,
} from "@modeling-kit/commands";
export type {
  CreatePrimitiveParams,
  CreatePrimitiveResult,
  ExtrudeFacesParams,
  ExtrudeFacesResult,
  InsetFacesParams,
  SubdivideFacesParams,
  FillBoundaryParams,
  BevelEdgesParams,
  LoopCutParams,
  DissolveEdgesParams,
  DissolveVertexParams,
  DissolveFaceCommandParams,
  CollapseEdgeParams,
  ReverseFaceWindingParams,
  BridgeLoopsParams,
  SplitEdgeParams,
  CutFaceParams,
  ProjectUvMode,
  ProjectUvParams,
  AssignMaterialSlotParams,
  AddMaterialSlotParams,
  ReorderMaterialSlotsParams,
  UpdateMaterialParams,
  CreateMaterialParams,
  AssignMaterialParams,
  ProjectUvsParams,
  PackUvsParams,
  SetSeamsParams,
  CreateSkeletonParams,
  CreateSkeletonResult,
  BindSkinParams,
  CreateClipParams,
  SetKeyframeParams,
  SetTransformsParams,
  ReparentParams,
  DuplicateObjectsParams,
  DuplicateObjectsResult,
  SetVisibilityParams,
  GroupObjectsParams,
  GroupObjectsResult,
  UngroupObjectsParams,
  CreateTextureParams,
  CreateTextureSetParams,
  UpdateTextureSetParams,
  BindMaterialTextureSetParams,
  CreateMaterialInstanceParams,
  UpdateMaterialInstanceParams,
  PaintStrokeParams,
  AddImageLayerParams,
  ApplyImageTilePatchesParams,
  RemoveImageLayerParams,
  UpdateImageLayerParams,
  RenameNodeParams,
  WeldVerticesParams,
  ExecuteKnifePlanParams,
  KnifeCutParams,
  CatmullClarkParams,
  ConnectVerticesParams,
  MergeVerticesParams,
  TriangulateFacesParams,
  ObjectSummary,
  SceneInspectionResult,
  SelectedSummary,
  FaceSelectFilter,
  VecDelta,
} from "@modeling-kit/commands";
export {
  createPbrMaterial,
  createStandardPbrMaterial,
  createUnlitMaterial,
  createMaterialSlot,
  validateStandardPbrMaterial,
  validateUnlitMaterial,
  validateMaterialDefinition,
  assertValidMaterial,
  MaterialLibrary,
  assignFaceMaterialSlot,
  assignMaterialSlots,
  addSlotToRecord,
  reorderSlotsInRecord,
  syncMeshSlotIndices,
} from "@modeling-kit/materials";
export type {
  CreatePbrMaterialOptions,
  CreateStandardPbrOptions,
  CreateUnlitOptions,
  MaterialDefinition,
  MaterialInstance,
  MaterialSlot,
  MaterialSlotTarget,
  MeshFace,
  PbrMaterialData,
  StandardPBRMaterial,
  UnlitMaterial,
  MaterialAlphaMode,
  AlphaMode,
  TextureBinding,
  TextureTransform,
} from "@modeling-kit/materials";
export {
  projectPlanarUv,
  projectBoxUv,
  projectCylindricalUv,
  projectSphericalUv,
  computeUvBounds,
  transformUvs,
  extractUvIslands,
  packUvs,
  projectUvs,
  setSeams,
  createUvEditor,
  UVEditor,
  DEFAULT_UV_CHANNEL,
  buildUvTopology,
  type PlanarProjectionOptions,
  type BoxProjectionOptions,
  type CylindricalProjectionOptions,
  type SphericalProjectionOptions,
  type TransformUvOptions,
  type UvBounds,
  type UvIsland,
  type UVViewData,
  type UVEditorPreset,
} from "@modeling-kit/uv";
export {
  insetFaces,
  subdivideFaces,
  weldVertices,
  bridgeLoops,
  bevelEdges,
  dissolveEdges,
  loopCut,
  collectQuadEdgeLoop,
  collectOrientedQuadEdgeLoop,
  previewLoopCut,
  splitEdge,
  cutFace,
  KnifeTool,
  LoopCutTool,
  ExtrudeTool,
  BevelTool,
  MergeTool,
  ModalToolSession,
  ToolManager,
  InteractionCoordinator,
} from "@modeling-kit/tools";
export type {
  InsetFacesResult,
  SubdivideResult,
  SubdivideOpResult,
  WeldResult,
  BridgeEdgesResult,
  BevelEdgesResult,
  DissolveEdgesResult,
  LoopCutResult,
  LoopCutPhase,
  SplitEdgeResult,
  CutFaceResult,
  KnifeEndpoint,
  EditorTool,
  InteractionClaim,
  ToolContext,
} from "@modeling-kit/tools";
export {
  getEditorToolDefinitions,
  listEditorToolNames,
  executeEditorTool,
  type EditorToolDefinition,
  type EditorToolResult,
  type EditorToolSuccess,
  type EditorToolFailure,
  type JsonSchemaObject,
  type ToolDefinition,
  type ToolExecutionResult,
} from "./ai";
export {
  SkeletonBuilder,
  evaluateWorldPose,
  skinPositions,
  normalizeWeights,
  type AddBoneOptions,
  type WorldPose,
  type PoseMap,
  type Bone,
  type BoneWeight,
  type MeshSkinningData,
  type Skeleton,
  type VertexSkinWeights,
} from "@modeling-kit/rigging";
export {
  AnimationClipBuilder,
  animationClipToDocumentClip,
  evaluateClip,
  evaluateDocumentClip,
  findKeyframeIndex,
  sampleTrack,
  type EvaluatedTransform,
  type AnimationClip,
  type AnimationInterpolation,
  type AnimationPath,
  type KeyframeTrack,
} from "@modeling-kit/animation";
export {
  TextureBuffer,
  PaintEngine,
  drawBrushDab,
  drawBrushLine,
  uvToPixel,
  paintSurfaceHit,
  interpolateFaceUv,
  type WrapMode,
  type BrushMode,
  type BrushOptions,
  type PixelColor,
  type TextureBufferData,
  type TextureTilePatch,
  type SurfaceHit,
} from "@modeling-kit/paint";
export {
  exportObj,
  importObj,
  exportObjWithReport,
  importObjWithReport,
  exportStlAscii,
  importStlAscii,
  importStlAsciiWithReport,
  stlExportReport,
  exportGltf,
  exportGlb,
  exportGltfWithReport,
  exportGlbWithReport,
  importGltf,
  type ObjExportOptions,
  type StlExportOptions,
  type StlImportResult,
  type GltfExportOptions,
  type GltfExportResult,
  type GlbExportResult,
  type GltfImportOptions,
  type GltfImportResult,
  type GltfImportSource,
  type ConversionReport,
} from "@modeling-kit/formats";
export {
  TransformGesture,
  cloneTransform,
  transformsNearlyEqual,
  type TransformDelta,
  type TransformRequest,
} from "@modeling-kit/transform";
export {
  snapToGrid,
  snapToPoints,
  snapIncrement,
  snapAngle,
  querySnap,
  querySnapTuple,
  type SnapResult,
} from "@modeling-kit/snapping";
export {
  AsyncComputePool,
  defaultComputePool,
  type TaskPayload,
  type TaskType,
  type TriangulateTaskPayload,
  type PackUvsTaskPayload,
  type ValidateTaskPayload,
  type WorkerTaskRequest,
  type WorkerTaskResponse,
  type WorkerTaskSuccessResponse,
  type WorkerTaskErrorResponse,
} from "@modeling-kit/workers";
export {
  Vector3,
  Matrix4,
  Quaternion,
  Euler,
  BoundingBox,
  Ray,
  identityTransform,
  transformToMatrix,
  matrixToTransform,
  type Vec3,
  type Quat,
  type TransformData,
} from "@modeling-kit/math";
export {
  brand,
  Emitter,
  createIdFactory,
  createSequenceIdFactory,
  type Brand,
  type DocumentId,
  type ObjectId,
  type MeshId,
  type VertexId,
  type EdgeId,
  type HalfEdgeId,
  type FaceId,
  type CornerId,
  type MaterialId,
  type BoneId,
  type AnimationId,
  type SkeletonId,
  type IdFactory,
  type EditorEvents,
} from "@modeling-kit/core";
export {
  MeshBuilder,
  HalfEdgeMesh,
  triangulateMesh,
  serializeMesh,
  deserializeMesh,
  cloneMesh,
  meshFingerprint,
  faceNormal,
  planKnifeCuts,
  executeKnifeCutPlan,
  executeKnifePlan,
  fillBoundary,
  catmullClarkSubdivide,
  type SerializedMesh,
  type TriangulatedMesh,
} from "@modeling-kit/mesh";
export {
  createModelDocument,
  serializeDocument,
  parseDocument,
  EntityStore,
  beginDocumentTransaction,
  applyMigrations,
  type ModelDocument,
} from "@modeling-kit/document";
export {
  SelectionManager,
  type SelectionSnapshot,
  type SelectionDomain,
} from "@modeling-kit/selection";
export {
  addNode,
  getNode,
  worldMatrix,
  reparent,
  restoreNode,
  setLocalTransform,
  effectiveVisibility,
  effectiveLocked,
  clearSceneChildren,
  type AddNodeInput,
  type ReparentMode,
} from "@modeling-kit/scene";
export {
  generateBox,
  generatePlane,
  generateGrid,
  generateDisc,
  generateCylinder,
  generateCone,
  generatePyramid,
  generateUvSphere,
  generateIcosphere,
  generateTorus,
  generateCapsule,
  generateRamp,
  generateStairs,
  generateArch,
  generateWall,
  generateColumn,
  generatePrimitive,
  primitiveDisplayNames,
  canonicalizePrimitiveType,
  boxPrimitive,
  boxDefaults,
  validateBoxParameters,
  type BoxParameters,
  type PrimitiveResult,
  type PrimitiveFaceGroups,
  type PrimitiveGenerator,
  type PrimitiveType,
  type PrimitiveCreateParams,
} from "@modeling-kit/primitives";
export { validateMesh, healMesh, type MeshValidationResult, type MeshIssue, type MeshCleanupReport } from "@modeling-kit/validation";
export {
  createInputEngine,
  InputEngine,
  defaultAxisBindings,
  defaultModelingKeymap,
  keyPacket,
  pointerPacket,
  wheelPacket,
  emptyModifiers,
  emptyAxes,
  pointerButtonFromEventButton,
  type ActionContext,
  type ActionId,
  type AxisKeyBinding,
  type ButtonState,
  type DispatchResult,
  type GestureFrame,
  type GestureHandlers,
  type InputAxes,
  type InputContext,
  type InputEngineOptions,
  type InputModifiers,
  type InputPacket,
  type InputVec2,
  type KeymapEntry,
  type KeyPacket,
  type PointerPacket,
  type WheelPacket,
} from "@modeling-kit/input";
export { uv, createSessionUvEditor } from "./uv";

