export {
  SelectionManager,
  type IdRemap,
  type ReplaceSelectionInput,
  type SelectionChangeListener,
} from "./manager";
export type { SelectionDomain, SelectionSnapshot } from "./types";
export {
  allElementIds,
  boundaryElementIds,
  edgeLoopIds,
  edgeRingIds,
  growElementIds,
  invertElementIds,
  linkedElementIds,
  shrinkElementIds,
  boxSelectIds,
  lassoSelectIds,
  marqueeContainmentFromDrag,
  lassoContainmentFromWinding,
  coplanarFaceIds,
  similarMaterialFaceIds,
  type MarqueeContainment,
  type ScreenSelectOptions,
} from "./topology";
export { createRayOccluder, type OcclusionSample, type RayOccluder } from "./occlusion";
export {
  defaultBackfaceMode,
  defaultHoverPickPolicy,
  defaultViewportRect,
  isFiniteVec3,
  isIdentityPick,
  isSurfacePick,
  pickSelectionTarget,
  PointerPickSessionStore,
  purposeNeedsSurface,
  refineFaceSurface,
  requireSurfacePick,
  resolveClickFromSession,
  resolvePickPolicy,
  classifyPickSession,
  createPickSession,
  type ClientRectLike,
  type ClickPickBackend,
  type HoverPickBackend,
  type HoverPickPolicy,
  type IdentityPickResult,
  type PickBackfaceMode,
  type PickPurpose,
  type PointPickApplyMode,
  type PointPickDomain,
  type PointPickRequest,
  type PointPickResult,
  type PointPickSource,
  type SelectionIntent,
  type SurfacePickResult,
  type ToolPickResponse,
  type ViewportRect,
  type FaceRefinementFailure,
  type FaceRefinementOutcome,
} from "./picking";
export type { VisibilityPickingAdapter } from "./visibility-picking";
export { applyPointPickToSelection } from "./apply-point-pick";
