export {
  MeshBuilder,
  type AddFaceOptions,
  type CubeFaceIds,
  type ManifoldPolicy,
  type MeshBuilderOptions,
} from "./builder";
export { HalfEdgeMesh } from "./half-edge-mesh";
export {
  triangulatePolygon,
  triangulatePolygonLoops,
  type PolygonTriangulation,
  type PolygonTriangulationOptions,
  type PolygonTriangulationStatus,
  type TriangulationBackendId,
  type TriangulationBackendUsed,
} from "./polygon-triangulation";
export { triangulateMesh, type TriangulateMeshOptions } from "./triangulate";
export {
  cloneMesh,
  deserializeMesh,
  meshFingerprint,
  restoreMesh,
  serializeMesh,
  type SerializedMesh,
} from "./serialize";
export { deleteFace, extrudeFaces, faceNormal, type ExtrudeFacesResult } from "./extrude";
export type {
  CornerRecord,
  EdgeRecord,
  EdgeCreaseWeight,
  FaceRecord,
  HalfEdgeRecord,
  MeshComponent,
  MeshFace,
  MeshKernelData,
  TriangulatedMesh,
  VertexRecord,
} from "./types";
export {
  bevelEdges,
  bridgeLoops,
  catmullClarkSubdivide,
  setEdgeCreaseWeights,
  repairEdgeCreaseWeights,
  readCreaseWeight,
  clampCreaseWeight,
  isValidCreaseWeight,
  requireCreaseWeight,
  CREASE_EPSILON,
  CREASE_WEIGHT_MAX,
  CREASE_WEIGHT_MIN,
  DEFAULT_MITER_LIMIT,
  collectQuadEdgeLoop,
  collectQuadEdgeRing,
  collectOrientedQuadEdgeLoop,
  previewLoopCut,
  loopCutFactors,
  factorOnOrientedEdge,
  connectVertices,
  createMeshOperationContext,
  runTransactionalMeshOp,
  cutFace,
  defaultAttributePolicy,
  defaultGeometryTolerance,
  dissolveEdge,
  dissolveEdges,
  dissolveFace,
  dissolveVertex,
  collapseEdge,
  reverseFaceWinding,
  addEdge,
  addFace,
  addVertex,
  deleteEdges,
  deleteFaces,
  deleteVertices,
  duplicateFaces,
  separateFaces,
  joinMeshes,
  trianglesToQuads,
  executeKnifeCutPlan,
  executeKnifePlan,
  fillBoundary,
  extrudeRegion,
  insetFaces,
  loopCut,
  mergeVertices,
  mergeVerticesByDistance,
  planKnifeCuts,
  planKnifeStroke,
  cutEndpointPoint,
  snapKnifePoint,
  meshSnapRadius,
  splitEdge,
  subdivideFaces,
  triangulateFaces,
  type AttributePropagationPolicy,
  type BevelEdgesRequest,
  type BevelEdgesResult,
  type BevelWidthMode,
  type BevelOverlapMode,
  type SimpleBevelMiterMode,
  type SimpleBevelOptions,
  type SetEdgeCreaseWeightsRequest,
  type RepairCreaseWeightsResult,
  type AddEdgeRequest,
  type AddEdgeResult,
  type AddFaceRequest,
  type AddFaceResult,
  type AddVertexRequest,
  type AddVertexResult,
  type DeleteEdgesRequest,
  type DeleteFacesRequest,
  type DeleteVerticesRequest,
  type DuplicateFacesRequest,
  type DuplicateFacesResult,
  type JoinMeshesRequest,
  type JoinMeshesResult,
  type SeparateFacesRequest,
  type SeparateFacesResult,
  type TrianglesToQuadsRequest,
  type TrianglesToQuadsResult,
  type BridgeEdgesResult,
  type BridgeLoopsOpResult,
  type FillBoundaryMethod,
  type FillBoundaryRequest,
  type FillBoundaryResult,
  type BridgeLoopsResult,
  type CatmullClarkRequest,
  type CatmullClarkResult,
  type ConnectVerticesRequest,
  type CutEndpoint,
  type CutFaceRequest,
  type CutFaceResult,
  type DissolveEdgeRequest,
  type DissolveEdgeResult,
  type DissolveFaceRequest,
  type DissolveFaceResult,
  type DissolveVertexRequest,
  type DissolveVertexResult,
  type CollapseEdgeRequest,
  type CollapseEdgeResult,
  type ReverseFaceWindingRequest,
  type ElementMapping,
  type ExtrudeFacesOpResult,
  type ExtrudeFacesRequest,
  type ExtrudeRegionRequest,
  type ExtrudeRegionResult,
  type GeometryTolerance,
  type InsetFacesOpResult,
  type InsetFacesRequest,
  type InsetFacesResult,
  type KnifeCutPlan,
  type KnifeExecuteResult,
  type KnifePlan,
  type KnifePlanCut,
  type KnifePlanHit,
  type KnifePlanRequest,
  type KnifePoint,
  type PlannedCut,
  type LoopCutRequest,
  type LoopCutResult,
  type LoopCutPreview,
  type OrientedLoopEdge,
  type MergeVertexTarget,
  type MergeVerticesRequest,
  type MergeVerticesResult,
  type MeshChangeSet,
  type MeshOperationContext,
  type MeshOperationResult,
  type MeshOperationWarning,
  type SelectionSuggestion,
  type SplitEdgeRequest,
  type SplitEdgeResult,
  type SubdivideOpResult,
  type SubdivideResult,
  type TopologyMapping,
  type TriangulateFacesRequest,
  type TriangulateFacesResult,
  type ValidationMode,
  type Vec3Tuple,
} from "./operations";
